admins:
  per_page: 10
posts:
  per_page: 5
  user_per_page: 6
  recent_page: 3
jobs:
  per_page: 10
slider_images:
  per_page: 9
company_info:
  mobile_phone: "078-595-9099 / 078-531-0291"
  email: "Jinzaishoukai@j-vconnection.com"
